/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_corda_core_crypto_FalconSignature */

#ifndef _Included_net_corda_core_crypto_FalconSignature
#define _Included_net_corda_core_crypto_FalconSignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_corda_core_crypto_FalconSignature
 * Method:    do_falcon_sign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_corda_core_crypto_FalconSignature_do_1falcon_1sign
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     net_corda_core_crypto_FalconSignature
 * Method:    do_falcon_verify
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_net_corda_core_crypto_FalconSignature_do_1falcon_1verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
