/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_corda_core_crypto_FalconKeyPairGenerator */

#ifndef _Included_net_corda_core_crypto_FalconKeyPairGenerator
#define _Included_net_corda_core_crypto_FalconKeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_corda_core_crypto_FalconKeyPairGenerator
 * Method:    do_falcon_keygen
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_corda_core_crypto_FalconKeyPairGenerator_do_1falcon_1keygen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
