/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_corda_core_crypto_MySignature */

#ifndef _Included_net_corda_core_crypto_MySignature
#define _Included_net_corda_core_crypto_MySignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_corda_core_crypto_MySignature
 * Method:    do_falcon_sign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_corda_core_crypto_MySignature_do_1falcon_1sign
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
